### ISSUE TITLE
Calling Formula.sha1 is deprecated

### ISSUE THREAD

**Issue by neo-apz** [yudai/gotty#110] opened 2016-08-01 16:44 UTC
Warning: Calling `Formula.sha1` is deprecated!
Use `Formula.sha256` instead.

**Comment by selfagency** [comment] 2016-08-02 00:02
+1

this is broken in homebrew

```bash
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/yudai/homebrew-gotty/gotty.rb:8:in `<class:Gotty>'
Please report this to the yudai/gotty tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/yudai/homebrew-gotty/gotty.rb:8:in `<class:Gotty>'
Please report this to the yudai/gotty tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/yudai/homebrew-gotty/gotty.rb:8:in `<class:Gotty>'
Please report this to the yudai/gotty tap!
```

**Comment by jasonchaffee** [comment] 2016-08-06 00:04
+1

**Comment by yudai** [comment] 2016-08-14 00:27
It's fixed now. Thanks for the report.

**Closed by yudai** 2016-08-14 00:27 UTC
Labels: bug

**Comment by selfagency** [comment] 2016-08-14 01:34
your tap is still pulling v0.0.12

**Comment by yudai** [comment] 2016-08-14 04:03
I cannot reproduce that. Could you try re-tap the repo?

**Comment by jasonchaffee** [comment] 2016-08-14 04:12
It worked for me too.  You need to do a brew update and brew upgrade.  Or, you can uninstall and untap and then tap again.  Both ways worked correctly for me.
