### ISSUE TITLE
Missing the hterm.js in resources/ folder.

### ISSUE THREAD

**Issue by codeskyblue** [yudai/gotty#60] opened 2015-09-15 08:51 UTC
May be you use go-bindata, even through this program can work, but hterm.js still not found.

**Comment by yudai** [comment] 2015-09-15 19:23
Yes. go-bindata is used. and hterm.js is not included in the repo because it's just an intermediate file and generated automatically by `make`.

**Comment by yudai** [comment] 2015-10-05 02:46
Closing as this is not a bug and the issue has been not updated recently.

**Closed by yudai** 2015-10-05 02:46 UTC
Labels: triage
