### ISSUE TITLE
ARM V5 request

### ISSUE THREAD

**Issue by nephaste** [yudai/gotty#55] opened 2015-09-04 16:35 UTC
Hi Master Yudai

the actual binary release is for ARM6, possible to have ARM5 version, i am sure some qnap user will love your application

thanks a lot ,

**Comment by Arno0x** [comment] 2015-09-04 16:55
Just as a side note: current GoTTY ARM release is suitable for the ARMv7 (Raspberry pi2). Not sure how many flavors of ARM architecture you can compile GoTTY for...

**Comment by nephaste** [comment] 2015-09-04 17:06
here is the output on my HS-210 Qnap test

runtime: this CPU has no floating point hardware, so it cannot run
this GOARM=6 binary. Recompile using GOARM=5.

**Comment by jungle-boogie** [comment] 2015-09-04 17:25
Can you compile from source?

**Comment by nephaste** [comment] 2015-09-04 18:16
not enought knownledge in go to do it.. i wonder if binaries for different ARM version could be available

**Comment by yudai** [comment] 2015-09-05 00:30
Created a test release for ARM5 architecture: https://github.com/yudai/gotty/releases/tag/pre-release
I myself cannot test it because I don't have an environment with a ARMv5 processor, so @nephaste,  could you try it out?
I'm not sure if this works on other ARM processors like ARMv7. If it has the forward-compatibility, I can change the default `GOARM` value to `5` so that a single binary can support all ARM processors.

**Comment by Arno0x** [comment] 2015-09-05 06:42
ARMv7 provides, as you could expect, new features, instruction set and performance. Even if an ARMv7 was backward compatible and able to run ARMv5 code, I think it would be a shame not to leverage from pure ARMv7 code...
http://infocenter.arm.com/help/topic/com.arm.doc.dai0425/DAI0425_migrating_an_application_from_ARMv5_to_ARMv7_AR.pdf

**Comment by yudai** [comment] 2015-09-05 07:20
@Arno0x  Thank you for sharing your concern. However, it's hard to maintain binaries for all ARM versions by default. There are already 4 versions (5 ~ 8) of ARM architectures and I don't want to make the file list in the releases page longer by supporting those different versions.
I assume there is no big impact to the performance of gotty by using ARMv5 as the default because gotty doesn't use floating values or SIMD instructions heavily (at all?).
As long as there is no large performance difference confirmed by actual benchmarks, I think that distributing the most compatible binary is the best way.

**Comment by nephaste** [comment] 2015-09-05 07:42
Hi yudai,

no problem, i could test the bianries on ARMV5, only five minute to make the QPKG and install it 

thanks for all

**Comment by nephaste** [comment] 2015-09-05 07:50
I confirm : https://github.com/yudai/gotty/releases/tag/arm5-test

is working great !!!! thanks a lot

**Comment by Arno0x** [comment] 2015-09-05 08:13
Hi, I tested this ARMv5 release on a ARMv7 architecture (Raspberry Pi 2) and as you could expect, it works. Just slightly bigger binary.  As Yudai said, I don't expect a big drop in performance due to the difference in the instruction set.

**Comment by yudai** [comment] 2015-09-05 08:19
@nephaste Thank you for testing. I'm glad to hear it worked :+1: 

@Arno0x Thank you for validating the binary on ARMv7. I'd like to go with ARMv5 by default. Let me know when you got a performance issue on Raspberry PI 2 in the future.

**Comment by yudai** [comment] 2015-09-17 05:36
Now ARMv5 is the default. Closing.

**Closed by yudai** 2015-09-17 05:36 UTC
Labels: enhancement, work in progress

**Comment by m040601** [comment] 2020-07-22 15:47
Just reporting that on July 2020,
the latest github precompiled binary release available,
that is, 2017 https://github.com/yudai/gotty/releases/tag/v2.0.0-alpha.3

is working fine on Raspbery Pi 2b v 1.1 (Armv7h)
