### ISSUE TITLE
curses-based application not working when upgrading from 1.0.0 to v2.0.0-alpha.1 

### ISSUE THREAD

**Issue by coljac** [yudai/gotty#163] opened 2017-08-23 04:44 UTC
### What version of GoTTY are you using (`gotty --version`)?
v2.0.0-alpha.1 (248f51b)

### What operating system and browser are you using?
gotty on ubuntu 16.04, browser = chrome on ubuntu 16.04

### What did you do?
I ran gotty wrapping a curses-based application (my own). The top two-thirds of the screen render ok, but then the bottom is corrupted, and resizing the screen (browser) does not fix it properly.

I can replicated this with Midnight Commander:

`sudo apt-get install mc`
`gotty -w mc`

### What did you expect to see?
Properly rendered file tree, command prompt at bottom

### What did you see instead?
Bottom third of the screen not rendered

Gotty 1.0.0 displays both applicions perfectly.

![midnight commander](https://user-images.githubusercontent.com/191407/29599207-8cc0e040-8811-11e7-810b-a5b7174e8c5d.png)

**Comment by yudai** [comment] 2017-08-23 05:40
@coljac  Thank you for the bug report.
I succeeded to reproduce the issue and  I think I found the root cause.
Give me some time to fix it.

**Comment by yudai** [comment] 2017-08-23 06:35
ok, should be fixed now. 

@coljac Let me know if you need a new binary. I'll build one for you.

**Comment by coljac** [comment] 2017-08-23 06:57
I updated and it works perfectly now. Thanks for the very quick fix!

**Comment by yudai** [comment] 2017-08-23 07:42
Thank you for confirmation! Closing as fixed.

**Closed by yudai** 2017-08-23 07:42 UTC
Labels: kind/bug, status/fix-in-master
