### ISSUE TITLE
Surface IP addresses of connected clients

### ISSUE THREAD

**Issue by thedockster** [yudai/gotty#61] opened 2015-09-19 12:35 UTC
It would be helpful if the IP addresses of the clients could be part of the logging. Working on an educational application for shared terminal window and it would help with debugging.

**Comment by booyaa** [comment] 2015-09-19 17:57
+1 on this idea, also if you could see the HTTP status code i.e. 404 it would mean I could use fail2ban to block bad behaviour. I've seen people trying to sniff out urls like

```
2015/09/18 20:30:22 GET /reader/about/
2015/09/18 20:37:06 GET //jmx-console/HtmlAdaptor
2015/09/18 23:48:56 GET /testproxy.php
```

I'm getting these attempt despite using the `--random-url` switch.

**Comment by yudai** [comment] 2015-09-20 01:44
Sounds a nice idea. I'll working on it soon.

**Comment by yudai** [comment] 2015-09-20 04:44
Implemented. Now it shows log like:

```
2015/09/20 13:42:39 10.1.1.150:61469 401 GET /
2015/09/20 13:42:39 10.1.1.150:61470 401 GET /favicon.ico
2015/09/20 13:42:42 Basic Authentication Succeeded: 10.1.1.150:61469
2015/09/20 13:42:42 10.1.1.150:61469 200 GET /
2015/09/20 13:42:42 Basic Authentication Succeeded: 10.1.1.150:61469
2015/09/20 13:42:42 Basic Authentication Succeeded: 10.1.1.150:61471
2015/09/20 13:42:42 10.1.1.150:61471 200 GET /js/gotty.js
2015/09/20 13:42:42 Basic Authentication Succeeded: 10.1.1.150:61470
2015/09/20 13:42:42 10.1.1.150:61470 200 GET /auth_token.js
2015/09/20 13:42:42 10.1.1.150:61469 200 GET /js/hterm.js
2015/09/20 13:42:42 New client connected: 10.1.1.150:61472
2015/09/20 13:42:42 Basic Authentication Succeeded: 10.1.1.150:61469
2015/09/20 13:42:42 10.1.1.150:61469 200 GET /favicon.png
2015/09/20 13:42:42 Command is running for client 10.1.1.150:61472 with PID 12872
2015/09/20 13:42:42 10.1.1.150:61472 101 GET /ws
2015/09/20 13:42:42 Basic Authentication Succeeded: 10.1.1.150:61469
2015/09/20 13:42:42 10.1.1.150:61469 304 GET /favicon.png
```

**Comment by booyaa** [comment] 2015-09-20 11:41
That's awesome! Thanks for such a quick turn around!

**Comment by yudai** [comment] 2015-10-05 02:46
Closing as the issue is solved :)

**Closed by yudai** 2015-10-05 02:46 UTC
Labels: enhancement, fix in pre-release
