### ISSUE TITLE
Ctrl-W, Ctrl-T and Ctrl-N are captured by Chrome and Firefox and do not work on Windows and Ubuntu

### ISSUE THREAD

**Issue by shohamp** [yudai/gotty#162] opened 2017-08-22 12:50 UTC
I'm using ctrl+w on the shell on a regular basis to delete the last word.
Every time I do, the tab is closed in the browser - very irritating.

Can you make the tty block the ctrl+w key, and make it actually delete the last word, like in a regular shell?

**Comment by yudai** [comment] 2017-08-22 19:41
Could you provide the version number of your gotty binary, browser and OS?
I currently cannot reproduce he issue on my environment with any browsers.

**Comment by shohamp** [comment] 2017-08-23 11:04
Sure.
gotty version is 0.0.12
Browser is chrome 60.0.3112.90 on Ubuntu 16.04.02
server is docker container running on CentOS 7.0.1406

**Comment by yudai** [comment] 2017-08-24 04:18
@shohamp Thanks for the info.
Unfortunately, I don't have a linux desktop environment right now. So I myself cannot reproduce your issue.
Do other key pairs with ctrl work on your environment?

**Comment by shohamp** [comment] 2017-08-24 08:27
Thanks for the reply.
I tested on Windows 7 x64 with Chrome 60.0.3112.101
I'm still experiencing the issue.

ctrl+c, ctrl+d, crtl+shift+v all work fine in the shell.
Only ctrl+w doesn't work.

**Comment by yudai** [comment] 2017-08-25 05:27
Thanks for the reply.
I confirmed that the issue happens on my Windows environment.

However, unfortunately, it's Chrome's limitation and we have no workaround for it.
You cannot use Ctrl-W, Ctrl-N and Ctrl-T on Chrome.

https://chromium.googlesource.com/chromiumos/platform/assets/+/95f6a2c7a984b1c09b7d66c24794ce2057144e86/chromeapps/hterm/doc/faq.txt#392

If you are ok to open your gotty window as an "application", you can use Ctrl-W. See https://superuser.com/a/33553 for how to make your gotty window into an chrome application.

It seems Firefox on Windows has the same issue. Edge doesn't have this limitation.

**Comment by yudai** [comment] 2017-08-25 05:33
On OSX, these Ctrl shortcuts work fine because the native window operations are assigned to shortcuts with Command.

**Comment by yudai** [comment] 2017-08-26 07:49
Closing as we don't have a way to fix this issue. 
@shohamp Thanks for the report!

**Closed by yudai** 2017-08-26 07:49 UTC
Labels: kind/issue-of-others, status/wontfix
